const CLOUD_DATA_KEY='patrimoine-v5.1';
const CLOUD_CONFIG_KEY='patrimoine-supabase-config';
const DEFAULT_SUPABASE_CONFIG={url:'https://srqvtcqntihkdxgpusjg.supabase.co',key:'sb_publishable_7CWSekc8w0DjY45Jbpab2A_D0k4xo8z'};
let cloudClient=null,cloudUser=null,cloudTimer=null,cloudBusy=false;
const originalStorageSet=Storage.prototype.setItem;
Storage.prototype.setItem=function(key,value){originalStorageSet.call(this,key,value);if(this===localStorage&&key===CLOUD_DATA_KEY)window.scheduleCloudSync?.()};
function cloudConfig(){try{const saved=JSON.parse(localStorage.getItem(CLOUD_CONFIG_KEY)||'{}');return{url:saved.url||DEFAULT_SUPABASE_CONFIG.url,key:saved.key||DEFAULT_SUPABASE_CONFIG.key}}catch{return DEFAULT_SUPABASE_CONFIG}}
function setCloudStatus(text,online=false){const s=document.querySelector('#cloudStatus'),b=document.querySelector('#cloudBadge');if(s)s.textContent=text;if(b){b.textContent=online?'☁️ Synchronisé':'☁️ Local';b.classList.toggle('cloud-online',online)}}
function initCloudClient(){const c=cloudConfig();if(!c.url||!c.key||!window.supabase){cloudClient=null;setCloudStatus('Cloud non configuré');return null}try{cloudClient=window.supabase.createClient(c.url,c.key,{auth:{persistSession:true,autoRefreshToken:true}});return cloudClient}catch{cloudClient=null;setCloudStatus('Configuration Supabase invalide');return null}}
async function currentSession(){if(!cloudClient)return null;const {data}=await cloudClient.auth.getSession();cloudUser=data.session?.user||null;updateCloudUI();return data.session||null}
function updateCloudUI(){const logged=!!cloudUser;document.querySelector('#cloudLoggedOut')?.classList.toggle('hidden',logged);document.querySelector('#cloudLoggedIn')?.classList.toggle('hidden',!logged);if(logged){document.querySelector('#cloudUserEmail').textContent=cloudUser.email||cloudUser.id;setCloudStatus('Connecté et synchronisé',true)}else if(cloudClient)setCloudStatus('Configuré — connexion requise')}
async function uploadCloudState(){if(!cloudClient||!cloudUser||cloudBusy)return;let payload;try{payload=JSON.parse(localStorage.getItem(CLOUD_DATA_KEY)||'null')}catch{return}if(!payload)return;cloudBusy=true;setCloudStatus('Synchronisation…',true);const {error}=await cloudClient.from('user_state').upsert({user_id:cloudUser.id,payload,updated_at:new Date().toISOString()},{onConflict:'user_id'});cloudBusy=false;if(error){console.error(error);setCloudStatus('Erreur de synchronisation')}else setCloudStatus('Synchronisé',true)}
window.scheduleCloudSync=function(){if(!cloudClient||!cloudUser)return;clearTimeout(cloudTimer);cloudTimer=setTimeout(uploadCloudState,700)};
async function loadCloudState(){if(!cloudClient||!cloudUser)return;const {data,error}=await cloudClient.from('user_state').select('payload,updated_at').eq('user_id',cloudUser.id).maybeSingle();if(error){console.error(error);setCloudStatus('Erreur de lecture cloud');return}if(data?.payload){const marker='cloud-loaded-'+cloudUser.id;if(sessionStorage.getItem(marker)!=='1'){originalStorageSet.call(localStorage,CLOUD_DATA_KEY,JSON.stringify(data.payload));sessionStorage.setItem(marker,'1');location.reload();return}setCloudStatus('Synchronisé',true)}else{await uploadCloudState()}}
async function signIn(){if(!cloudClient)return alert('Configure d’abord Supabase.');const email=document.querySelector('#cloudEmail').value.trim(),password=document.querySelector('#cloudPassword').value;if(!email||!password)return alert('Renseigne l’e-mail et le mot de passe.');const {data,error}=await cloudClient.auth.signInWithPassword({email,password});if(error)return alert(error.message);cloudUser=data.user;sessionStorage.removeItem('cloud-loaded-'+cloudUser.id);updateCloudUI();await loadCloudState()}
async function signUp(){if(!cloudClient)return alert('Configure d’abord Supabase.');const email=document.querySelector('#cloudEmail').value.trim(),password=document.querySelector('#cloudPassword').value;if(!email||password.length<6)return alert('Renseigne un e-mail et un mot de passe d’au moins 6 caractères.');const {data,error}=await cloudClient.auth.signUp({email,password});if(error)return alert(error.message);if(data.session){cloudUser=data.user;updateCloudUI();await uploadCloudState();alert('Compte créé et connecté.')}else alert('Compte créé. Vérifie ton e-mail si Supabase demande une confirmation, puis connecte-toi.')}
async function signOut(){if(cloudClient)await cloudClient.auth.signOut();cloudUser=null;sessionStorage.clear();updateCloudUI();setCloudStatus('Déconnecté — données locales conservées')}
function saveCloudConfig(){const url=document.querySelector('#supabaseUrl').value.trim(),key=document.querySelector('#supabaseAnon').value.trim();if(!url||!key)return alert('Renseigne l’URL Supabase et la clé publique.');originalStorageSet.call(localStorage,CLOUD_CONFIG_KEY,JSON.stringify({url,key}));initCloudClient();currentSession();alert('Configuration cloud enregistrée.')}
window.addEventListener('DOMContentLoaded',async()=>{const c=cloudConfig();document.querySelector('#supabaseUrl').value=c.url||'';document.querySelector('#supabaseAnon').value=c.key||'';document.querySelector('#saveCloudConfigBtn').onclick=saveCloudConfig;document.querySelector('#cloudLoginBtn').onclick=signIn;document.querySelector('#cloudSignupBtn').onclick=signUp;document.querySelector('#cloudLogoutBtn').onclick=signOut;document.querySelector('#cloudSyncBtn').onclick=async()=>{await uploadCloudState();await loadCloudState()};initCloudClient();const session=await currentSession();if(session)await loadCloudState();});